### ISSUE TITLE
Pandoc error, unexpected "%"

### ISSUE THREAD

**Issue by jtbates** [GarenSidonius/ASU-Dissertation-Template#10]
I'm trying to compile with pandoc and I get the following error:
```
$ pandoc -s dissertation_template_latex_sample.tex -o dissertation_template_latex_sample.text
pandoc:
Error at "source" (line 17, column 41):
unexpected "%"
expecting "[", lf new-line, "{" or "\\"
               \pointsize]              % Uses the font size defined above
                                        ^
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Error.hs:66:13 in pandoc-1.19.2.1-J1nmFBg9ln971v0RrPbKLJ:Text.Pandoc.Error
```

I get the same error if I try to output to pdf rather than markdown.

**Comment by GarenSidonius** [comment]
A few points to make here: 

[1] 
I'm not sure what you're trying to achieve with the command above. If you're trying to convert the sample TeX file to plain text, I think it would look something like: 

    pandoc -r latex -w plain dissertation_template_latex_sample.tex -o output.txt 

[2] 
The goal of this git repository is to provide ASU graduate students with an easy-to-use LaTeX template that conforms to ASU's style guide. In other words, Pandoc support would be nice, but I haven't specifically included it. 

[3] 
As a result, this repository does not contain a Pandoc template. A Pandoc template would need to have certain variables in the template. I recommend to view Pandoc's default LaTeX template to see what's needed in such a template. (See the Pandoc documentation on the `-D/--print-default-template` option for guidance on outputting Pandoc's default templates.) 

If you're interested to convert the existing LaTeX template in this repository to a Pandoc template, I would love to include that in the repository. I would have done it myself but haven't found the time for it.

**Comment by jtbates** [comment]
[1] I was trying to output to Markdown so that the files would be rendered by GitHub.
[2] I see. I thought since that the readme mentioned Pandoc that it might work.
[3] Thanks for the pointer. I will look into it.
