### ISSUE TITLE
AfterEndEnvironment need to be redifined in the back matter

### ISSUE THREAD

**Issue by piyanatk** [GarenSidonius/ASU-Dissertation-Template#11]
In the back matter, `table`, `figure`, `quote` and `quotation` environments need to be re-set to use single spacing after the environment. Else, previous definitions will force the back matter into double spacing if, for example, a figure is placed inside the appendix.

**Comment by GarenSidonius** [comment]
This sounds like a straightforward fix. Do you happen to have a sample file that demonstrates the problem? That way I can make updates and confirm the fixes using your sample.

**Comment by piyanatk** [comment]
Sure. I basically add the four lines below to the beginning of the back matter

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Back matter
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Reset 
\AfterEndEnvironment{table}{\SingleSpacing}
\AfterEndEnvironment{figure}{\SingleSpacing}
\AfterEndEnvironment{quote}{\SingleSpacing}
\AfterEndEnvironment{quotation}{\SingleSpacing}

\SingleSpacing                          % Back matter should be single spaced
```
Here are screen shorts before and after this fix, using `quote` environment as an example.

Before
![Screen Shot 2019-03-29 at 9 46 48 AM](https://user-images.githubusercontent.com/2381361/55248861-ea42b600-5207-11e9-9edf-7ce4e4a3ff11.png)

After
![Screen Shot 2019-03-29 at 9 47 11 AM](https://user-images.githubusercontent.com/2381361/55248872-f2025a80-5207-11e9-8430-eb45ab765c21.png)

**Comment by GarenSidonius** [comment]
Fantastic, thanks for providing all of that! I've incorporated these changes: 3ad53e5c3fb18e47a293d04658c47880ba5156fc
