### ISSUE TITLE
Request for comment: Feedback on this template

### ISSUE THREAD

**Issue by GarenSidonius** [GarenSidonius/ASU-Dissertation-Template#13]
I've been getting a lot more email questions and traffic on this template recently, so it might be the case that it's becoming more popular. I'm not sure, but I would like to check with people who have used or are using the template: What is your feedback? 

I occasionally get feature requests for specific updates, but here, I'm more interested in getting general feedback about the template. Are there general features that are missing? (I'm thinking of things like adding a pandoc template, integrating with R bookdown, etc.) 

The goal of this project is to make thesis/dissertation formatting as easy as possible for grad students, so that's the guiding principle for this work.

**Comment by piyanatk** [comment]
Hi Robert,

My immediate feedback is that the template works very well although there are still some minor issues that should to be fixed. (I will follow up on these.)  

My main concern is that it is not very friendly for users with  little experience with latex. Many students are forced to use latex to write their dissertation because of the specific formatting and the length of the documents. I think it might be best if the template is provided as a class style file with an example template written as a user guide (see [UW's template](https://staff.washington.edu/fox/tex/uwthesis.shtml) for example). 

I do not have experience with writing a class file, but I can perhaps help you test it while learning how it work, and I can definitely help writing a user guide.

-Piyanat

**Comment by GarenSidonius** [comment]
Thanks for your feedback. Do you know many students that have gotten tripped up with LaTeX? I can imagine it might be the case, but I could also imagine that people who are uninterested in LaTeX might just use Word. It would be great to hear from others on this point, too, so we could get a sense for how widespread this feedback is. 

If it is the case that students struggle with LaTeX, I think the better way to help them would be to provide a pandoc template. That would allow them to write most or maybe all of their text in markdown and have it automatically converted to LaTeX and ultimately a PDF. Markdown has much more user-friendly syntax, so I would expect it to be much easier for a more general audience to adopt. With a pandoc template, users might need to mix a little LaTeX into their markdown to customize things, but needing to do so would be minimized. 

A document class would provide a better user interface to the template itself, but I'm not sure there's enough of a payoff there to justify the time and effort for developing it. A document class does not get students out of having to learn LaTeX for all the rest of their writing (chapters with paragraphs, lists, tables, figures, etc.). Students would still need to know enough LaTeX to do all of that. The document class only simplifies putting information into the template, and I've already marked out which lines in the templates can and should be edited (so hopefully that's not too difficult). Don't get me wrong: If someone wants to write a document class for this, I am happy to put it in the repo, but in terms of my own time and effort, I'm not sure yet whether the payoff is there. But I'm open to being persuaded on this if I get the sense that a lot of people want and would get a lot of value out of a document class.

**Comment by piyanatk** [comment]
You are right that the student will probably choose Word if they have no background with Latex.

Pandoc sounds good if you already know Markdown. Having to lean another document markup language when you need to get your thesis done is not ideal. I doubt many students will chose to go that route.

I think what we, the students, really need is a user guide, written with the template, to explain what need to be changed, why, and how to troubleshoot. It will also serve as a recap on the basic Latex syntax. I am willing to write one to contribute to the repo during the Summer.

As for number of users, I think most students are using this template although I do not know the exact number. ASU Formatting Guideline links to John Shumway's template, which links to this template as it no longer produce the right format. ASU formatting office is aware of this template now, and they will probably link to it in the following semester.

**Comment by GarenSidonius** [comment]
I wouldn't include LaTeX basics because I agree (at least in this case) with the Unix philosophy of "do one thing and do it well." There are plenty of resources on the Internet for learning LaTeX basics (one of which is already linked in the readme), and I don't want to be responsible for maintaining another one in this repository. The focus of this repository is providing user-friendly formatting for ASU's graduate work documents. 

From my perspective, a user guide is a bit of a gray area. The template itself is already self-documenting via comments throughout, and lines that need or optionally take user input are marked specifically as such. Using comments throughout is not ideal, but a user guide would be an entirely new document to maintain and keep in sync with everything else, so ... I'm hesitant. If there was something of a build system to keep the user guide in sync with the template itself, I'd be less hesitant. So a documentclass with documentation would be better than a separate user guide. 

The more I think about it, though, the less I like a documentclass. ASU's dissertation guidelines aren't just about formatting (margins, fonts, vertical spacing, etc.); they're also about the *order* of various elements in the document. So we can give users commands for outputting a properly formatted preface, but they would still need to select the correct placement for it themselves. The template takes care of all of that so that students can just drop in their content with as little thought to the whole process as possible. I don't know, I'm still thinking about this ...

**Comment by GarenSidonius** [comment]
After several months, there haven't been comments from other users requesting new resources (e.g., a documentclass or a pandoc template). So I don't see evidence that investing the time and effort to develop either of those (or something else) would bring enough benefit to students who use this template. 

Users are free to open a new issue if they would like to request either of those or something else.
