### ISSUE TITLE
Adding theorem and definition commands

### ISSUE THREAD

**Issue by ryandougherty** [GarenSidonius/ASU-Dissertation-Template#2]
A feature that would be really useful would be to add theorems/definitions to the main file:

\usepackage{amsthm} % for theorem
\theoremstyle{definition}
\newtheorem{definition}{Definition}[section]
\newtheorem{theorem}{Theorem}[section]
\newtheorem{corollary}{Corollary}[theorem]
\newtheorem{lemma}[theorem]{Lemma}

**Comment by GarenSidonius** [comment]
I was going to wait to see if others were interested in this, but I might just add it anyway. 

Did you pass format review with the code you pasted above?

**Comment by GarenSidonius** [comment]
No stated interest in this in over a year. Closing this ticket.
