### ISSUE TITLE
Unnecessary extra spacing between paragraphs due to figures.

### ISSUE THREAD

**Issue by jdaymude** [GarenSidonius/ASU-Dissertation-Template#25]
First off, a huge thank you for putting this together. Would have been a lot of effort in an already stressful season to put something even half as good together myself.

I'm running into a small issue with paragraph spacing. Suppose we have the following:

```
First paragraph of text, lorem ipsum...

\begin{figure}
    \centering
    \includegraphics{...}
    \caption{...}
    \label{...}
\end{figure}

Second paragraph of text, lorem ipsum...
```

There are two cases. If LaTeX puts the figure "here" (i.e., what you'd get with the `[h]` float hint), then everything works well. But if LaTeX puts the figure elsewhere (e.g., at the top of the page or on the next page), the first and second paragraph will be separated by whitespace that is larger than double-spaced text but smaller than `\baselineskip`. In my mind, correct behavior for the second case should be a simple continuation of double-spaced text. Is there a way to enforce this?

**Comment by jdaymude** [comment]
An actual example from my dissertation. Consider the following snippet.

```
% ...
Inactive tokens are simply passed on until reaching the next candidate that reactivates it when passing it into the next segment, as already described (\figtext~\ref{fig:leaderelection:idcomp}d).

\begin{figure}[tbh]
    \centering
    \includegraphics[width=0.9\textwidth]{src/graphics/leaderelection/idcomparison.pdf}
    \caption[Identifier Comparison.]{Identifier Comparison.
    Candidate $c$ with identifier $c.\id = 0101$ is being compared to the token sequence of candidate $c'$ with $c'.\id = 1110$.
    Inactive elements are shaded while active elements are not.
    The digit tokens are depicted as squares, while the star depicts the special delimiter token.}
    \label{fig:leaderelection:idcomp}
\end{figure}

The delimiter token of the token sequence of $c'$ eventually enters $c.\seg$ (\figtext~\ref{fig:leaderelection:idcomp}d).
% ...
```

This produces the following, with the extra space between paragraphs due to the figure being placed at the top of the following page.

![image](https://user-images.githubusercontent.com/44209063/99888048-b4391d80-2c06-11eb-851d-8cf6fd7c2720.png)

**Comment by GarenSidonius** [comment]
@jdaymude 

> In my mind, correct behavior for the second case should be a simple continuation of double-spaced text. Is there a way to enforce this?

I'm not sure. The template contains this:

```
%%% Figures %%%
\setfloatadjustment{figure}%            % Left justify material inside figure floats
  {\raggedright}
\BeforeBeginEnvironment{figure}%        % Single space inside figure environment
  {\SingleSpacing}
\AfterEndEnvironment{figure}
  {\DoubleSpacing}
```

which might affect the vertical spacing. But overall, I'm not sure. I would recommend to Google around and play with settings to see if there's a solution. When troubleshooting things like this, it often helps to make a minimum working example (i.e., the smallest document that demonstrates the problem) and play with solutions from there.

Does it work better if you remove all the figure options (i.e., remove `[tbh]`)? 

If there's no workaround and it gets in the way of finishing the project, let me know, and I'll see if I can dig in further.

**Comment by jdaymude** [comment]
@GarenSidonius

> I'm not sure. The template contains this:
> 
> ```
> %%% Figures %%%
> \setfloatadjustment{figure}%            % Left justify material inside figure floats
>   {\raggedright}
> \BeforeBeginEnvironment{figure}%        % Single space inside figure environment
>   {\SingleSpacing}
> \AfterEndEnvironment{figure}
>   {\DoubleSpacing}
> ```

Interestingly, commenting out these lines entirely maintains the single-spaced figure captions and double-spaced main text while also fixing my extra spacing issue. It does however introduce a complementary spacing problem related to your question:

> Does it work better if you remove all the figure options (i.e., remove `[tbh]`)?

For figures placed with the "here" (`[h]`) float hint, which places figures as close to their in-line position as possible, the double-spacing between the preceding text and the top of the figure is now *removed* (the opposite behavior of what was happening before, where extra space was being added between the end of the figure and the following text). However, this can be worked around by:

1. Using "top" float hints (`[t]`) whenever appropriate since those figures do not experience this issue.
2. Adding `\vspace{\baselineskip}` to the top of every figure that needs a `[h]` option, as in:

```
Lorem ipsum...

\begin{figure}[h]
    \vspace{\baselineskip}
    \centering
    \includegraphics{...}
    \caption{...}
    \label{...}
\end{figure}

Lorem ipsum...
```

Thanks for your help!
