### ISSUE TITLE
Include 5 line skips after author name on title page instead of 4

### ISSUE THREAD

**Issue by jdaymude** [GarenSidonius/ASU-Dissertation-Template#29]
According to Page 5 of the [ASU Graduate College Format Manual](https://graduate.asu.edu/sites/default/files/asu-graduate-college-format-manual.pdf) (last updated January 2017), there should be 5 single line spaces between the author's name and the phrase "A Dissertation Presented in Partial Fulfillment".

So line 232 of `dissertation_template_latex.tex` should read:
```
\Author \\[5\baselineskip]
```
instead of:
```
\Author \\[4\baselineskip]
```

Apologies for a very nit-picking issue, but hopefully this is an easy fix!

**Comment by GarenSidonius** [comment]
Thanks @jdaymude , it's an easy change; did the Graduate College ask you for this change?

**Comment by jdaymude** [comment]
@GarenSidonius They did, which was easy to do in my own local version. Hopefully it will be an easy fix for the main repo.

**Comment by GarenSidonius** [comment]
@jdaymude Okay got it, thanks. I'll try to close this today
