### ISSUE TITLE
Using Overleaf

### ISSUE THREAD

**Issue by abshafique** [GarenSidonius/ASU-Dissertation-Template#3]
Hi, 
I am using Overleaf to write my Dissertation at ASU. I wanted to use your template package. But overleaf is showing an error  as follows

/usr/share/texlive/texmf-dist/tex/latex/biblatex-chicago/biblatex-chicago.sty: Package biblatex Warning: Since you are using the 'memoir' class, (biblatex) I'm leaving the formatting of the foot- and/or (biblatex) end-note mark and text to you..

**Comment by Mahdisadjadi** [comment]
Could you try to put `\footmarkstyle{#1.\,}` right after `\documentclass[letterpaper,oneside,             \pointsize] {memoir}` in `dissertation_template_latex.tex` file?

**Comment by abshafique** [comment]
That did not get rid of the warning message. ASU is very picky with their formatting, so I do not want to proceed without ensuring everything is without warnings.

**Comment by GarenSidonius** [comment]
Your PDF should still make without any problems. The message you're seeing is a warning (not a fatal error), just letting you know that memoir will control formatting for footnotes and endnotes. That's the behavior that you want. So this is just for information and shouldn't impact your ability to make PDFs. Does Overleaf prevent you from making the PDF? If not, you should be fine to proceed.

**Comment by abshafique** [comment]
The PDF does get generated. I was wondering if it would cause formatting issues.

One more thing,  I tried editing 
` \usepackage[authordate,%                 
              backend=biber,%           % Recommend to use 'biber' instead of 'bibtex'
              doi=only,%                % Avoid printing URLs
              isbn=false]%              % Don't print ISBN numbers
              {biblatex-chicago}        %~Other possibilities include: 'biblatex', 
                                        %   'biblatex-apa', and 'biblatex-mla'`
to "biblatex-apa" and get this error. This is a fatal error.

! LaTeX Error: File `biblatex-apa.sty' not found. l.715 } ^^M

How can I call apa style for references?

**Comment by GarenSidonius** [comment]
That error message indicates that Overleaf does not automatically make biblatex-apa.sty available. So you will most likely need to manually download it from CTAN (https://www.ctan.org/pkg/biblatex-apa) and upload biblatex-apa.sty to your Overleaf project.

**Comment by abshafique** [comment]
I have exhaustively searched through the CTAN link but did not find a bibtex-apa.sty file. Could you provide the link or the file please?

**Comment by GarenSidonius** [comment]
I provided a link in my previous comment.

**Comment by abshafique** [comment]
I'm sorry but I did not find the specific sty file in that link. If I download the zip file, that only contains lbx files. Are those the same as .sty?

I'm not adept at using Latex so am facing some issues here.

**Comment by GarenSidonius** [comment]
Oh gosh, you're right. Sorry about that. This is really an issue that you should bring to Overleaf since it's nothing to do with the template itself. They should be able to quickly tell you the best way to use biblatex-apa on their platform. You could also switch over to ShareLaTeX, which should make the template correctly without this problem. Alternatively, see the Readme for recommendations on setting up LaTeX on your local computer.

**Comment by abshafique** [comment]
Just so you know, in the past I have been able to create projects in Overleaf where all I had to do was use
\bibliographystyle{apa}
\bibliography{MyBibFile}

and the references would come out in the APA style correctly. Is there a way I can modify your code to do that?

**Comment by GarenSidonius** [comment]
Closing this issue as the original topic has been resolved

**Comment by abshafique** [comment]
I wanted to inform you that I uploaded the template to sharelatex and even here, If i try to use biblatex-apa there is an error message saying it cannot find the style file.

Additonally, I tried compiling on my desktop using Tex Studion and the latest Miktex and I am having multiple package related issues.

**Comment by GarenSidonius** [comment]
You can open new tickets for these issues if you would like help with them.
