### ISSUE TITLE
Adding a List of Symbols/ NomenClature

### ISSUE THREAD

**Issue by sssaha** [GarenSidonius/ASU-Dissertation-Template#30]
Hello I am trying to add a List of Symbol Table to the table of content. I am using the nomencl package (https://www.overleaf.com/learn/latex/Nomenclatures) with intoc enabled. But the nomenclature in TOC shows up after the chapter heading. What is the solution for this? 
How should I add a table of acronym for my thesis?

**Comment by GarenSidonius** [comment]
I can't promise I'll be able to solve this, but I can take a look and see if I can help. Would you be able to post a minimum working example showing the current problem?

**Comment by GarenSidonius** [comment]
Closing as stale
