### ISSUE TITLE
Headers are automatically generated at the top of each page. 

### ISSUE THREAD

**Issue by kathrynmi** [GarenSidonius/ASU-Dissertation-Template#34]
Apparently this issue only happens with the ASU Format Wizard, and not with the tex file from this github page.

**Comment by GarenSidonius** [comment]
Sorry @kathrynmi , I'm only supporting the TeX file in this git repository; I'm not familiar with ASU's Format Wizard. Hopefully ASU can fix their Formatting Wizard, but I'm not sure how well supported that tool is.
