### ISSUE TITLE
Template puts page number in wrong place

### ISSUE THREAD

**Issue by ErikPoppleton** [GarenSidonius/ASU-Dissertation-Template#36]
Hi,

I recently submitted my dissertation to the formatting committee but they will not accept it because the template is putting the page numbers in the wrong place.  The bottom of the page number is supposed to be on the 1" from bottom gridline, however the template puts it the top of the page number on the grid line.

![image](https://user-images.githubusercontent.com/36451772/174412941-dbdff9e1-c7dc-4b3a-8067-7cdc028d55d4.png)

I have tried changing the `\setulmargin` and `\textblockheight` in this block, but the bottom margin either ends up being way too large with the number above the line or under the line as shown in my screenshot.
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Page layout
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\settrimmedsize{\stockheight}%          % Specifies \paperheight and \paperwidth
  {\stockwidth}{*}
\settrims{0pt}{0pt}                     % Set location of page in relation to the stock.
                                        % Paper and stock size are equivalent,
                                        % so both \trimtop and \trimedge are set to 0pt
\newlength{\forfootskip}
\setlength{\forfootskip}%
  {3\baselineskip}
\newlength{\textblockheight}            % Calculate height of text block to leave room
\setlength{\textblockheight}{9.0in}     %   for footers, keeping page numbers outside
\addtolength{\textblockheight}%         %   the 1in vertical margins
  {-\forfootskip}
\settypeblocksize{\textblockheight}%    % Calculated by 1.0in vertical margins and
  {*}{*}                                %   letting margins set the width of the typeblock
\setulmargins{1.0in}{*}{*}              % Set upper margin (\uppermargin, not \topmargin);
                                        %   calculate the bottom margin
\setlrmarginsandblock{1.25in}{1.25in}{*}%~Set margins and calculate width of typeblock
\setheaderspaces{*}{0.5\baselineskip}{*}% Arguments: '\headdrop', '\headsep', and/or ratio
                                        %   Note: This is only used in the list of
                                        %   contents sections
\setheadfoot{\baselineskip}%            % Set '\headheight' and '\footskip'
  {\forfootskip}
\checkandfixthelayout                   % Required by memoir package after setting layout
\settypeoutlayoutunit{in}               % Write layout dimensions to log file in inches
```

**Comment by ErikPoppleton** [comment]
By changing the textblock height and removing the space for the footer I was able to get it more-or-less right:
```\setlength{\textblockheight}{8.5in}     %   for footers, keeping page numbers outside
%\addtolength{\textblockheight}%         %   the 1in vertical margins
%  {-\forfootskip}
```
This solution probably won't work for people who need footers for their document.


![image](https://user-images.githubusercontent.com/36451772/174653836-edd28d61-10a3-4a00-b599-b7f953112fb4.png)

**Comment by GarenSidonius** [comment]
Hi @ErikPoppleton , it seems like the problem is a difference between the PDFs produced by Docker and Overleaf. Here is a page from the sample PDF made with Docker:

![samplePDF_page14-measured](https://user-images.githubusercontent.com/4180070/175780581-b6d94cff-3897-432a-9034-ad0cf69b1c43.png)

Imported into GIMP at 100px per inch. The page number sits an inch above the bottom of the page.
